import { ModeIcon } from "@/components/ModeIcon";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import type { AppMode, ReasoningStyle } from "@/types";
import { Check, Copy } from "lucide-react";
import { useState } from "react";

interface ParsedSection {
  key: string;
  heading: string;
  body: string;
  isH1?: boolean;
}

function parseResponse(response: string): ParsedSection[] {
  const lines = response.split("\n");
  const sections: ParsedSection[] = [];
  let current: ParsedSection | null = null;
  let idx = 0;
  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current) sections.push(current);
      current = { heading: line.slice(3), body: "", key: `s${idx++}` };
    } else if (line.startsWith("# ")) {
      if (current) sections.push(current);
      current = {
        heading: line.slice(2),
        body: "",
        isH1: true,
        key: `h${idx++}`,
      };
    } else if (current) {
      current.body = `${current.body}\n${line}`.trim();
    }
  }
  if (current) sections.push(current);
  return sections;
}

function formatTimestamp(ts: number) {
  return new Date(ts).toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });
}

interface ResponseCardProps {
  response: string;
  mode: AppMode;
  reasoningStyle: ReasoningStyle;
  timestamp?: number;
}

export function ResponseCard({
  response,
  mode,
  reasoningStyle,
  timestamp,
}: ResponseCardProps) {
  const [copied, setCopied] = useState(false);
  const sections = parseResponse(response);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(response);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fade-in h-full flex flex-col" data-ocid="response.card">
      {/* Card header */}
      <div className="flex items-center gap-2 pb-3 mb-3 border-b border-border">
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
          <ModeIcon mode={mode} size={12} className="text-primary" />
          <span className="font-display">{mode}</span>
          <span>·</span>
          <span className="font-display">{reasoningStyle}</span>
          {timestamp && (
            <>
              <span>·</span>
              <span>{formatTimestamp(timestamp)}</span>
            </>
          )}
        </div>
        <Badge
          variant="outline"
          className="ml-auto text-[10px] h-5 font-display border-primary/30 text-primary/70"
        >
          Paradox.ai
        </Badge>
        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-2 py-1 rounded-md text-xs text-muted-foreground hover:text-foreground hover:bg-muted/60 transition-smooth"
          aria-label="Copy response"
          data-ocid="response.copy_button"
        >
          {copied ? (
            <Check size={12} className="text-primary" />
          ) : (
            <Copy size={12} />
          )}
          <span className="font-display">{copied ? "Copied" : "Copy"}</span>
        </button>
      </div>

      {/* Response content */}
      <ScrollArea className="flex-1">
        <div className="space-y-5 pr-1">
          {sections.map((section) => (
            <div
              key={section.key}
              className={section.isH1 ? "" : "accent-border-left pl-3"}
            >
              {section.isH1 ? (
                <h2 className="accent-text text-lg font-display font-medium mb-2">
                  {section.heading}
                </h2>
              ) : (
                <>
                  <h3 className="text-sm font-display font-medium text-primary mb-2">
                    {section.heading}
                  </h3>
                  <p className="text-sm text-foreground/80 leading-relaxed font-body">
                    {section.body}
                  </p>
                </>
              )}
            </div>
          ))}
          <Separator className="my-2" />
          <p className="text-[10px] text-muted-foreground font-display pb-2">
            Generated by Paradox.ai · {mode} mode · {reasoningStyle} reasoning
          </p>
        </div>
      </ScrollArea>
    </div>
  );
}
