/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntryId = IDL.Nat;
export const Mode = IDL.Variant({
  'Analytics' : IDL.Null,
  'Text' : IDL.Null,
  'Image' : IDL.Null,
  'Music' : IDL.Null,
  'Video' : IDL.Null,
});
export const ReasoningStyle = IDL.Variant({
  'Creative' : IDL.Null,
  'Technical' : IDL.Null,
  'Analytical' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const HistoryEntry = IDL.Record({
  'id' : EntryId,
  'mode' : Mode,
  'reasoningStyle' : ReasoningStyle,
  'response' : IDL.Text,
  'timestamp' : Timestamp,
  'prompt' : IDL.Text,
});
export const Theme = IDL.Variant({ 'Light' : IDL.Null, 'Dark' : IDL.Null });
export const UserSettings = IDL.Record({
  'theme' : Theme,
  'defaultMode' : Mode,
  'defaultReasoningStyle' : ReasoningStyle,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'deleteHistoryEntry' : IDL.Func([EntryId], [IDL.Bool], []),
  'getHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'saveHistoryEntry' : IDL.Func(
      [IDL.Text, Mode, ReasoningStyle, IDL.Text],
      [EntryId],
      [],
    ),
  'saveSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntryId = IDL.Nat;
  const Mode = IDL.Variant({
    'Analytics' : IDL.Null,
    'Text' : IDL.Null,
    'Image' : IDL.Null,
    'Music' : IDL.Null,
    'Video' : IDL.Null,
  });
  const ReasoningStyle = IDL.Variant({
    'Creative' : IDL.Null,
    'Technical' : IDL.Null,
    'Analytical' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const HistoryEntry = IDL.Record({
    'id' : EntryId,
    'mode' : Mode,
    'reasoningStyle' : ReasoningStyle,
    'response' : IDL.Text,
    'timestamp' : Timestamp,
    'prompt' : IDL.Text,
  });
  const Theme = IDL.Variant({ 'Light' : IDL.Null, 'Dark' : IDL.Null });
  const UserSettings = IDL.Record({
    'theme' : Theme,
    'defaultMode' : Mode,
    'defaultReasoningStyle' : ReasoningStyle,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'deleteHistoryEntry' : IDL.Func([EntryId], [IDL.Bool], []),
    'getHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'saveHistoryEntry' : IDL.Func(
        [IDL.Text, Mode, ReasoningStyle, IDL.Text],
        [EntryId],
        [],
      ),
    'saveSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };