/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EntryId = bigint;
export interface HistoryEntry {
  'id' : EntryId,
  'mode' : Mode,
  'reasoningStyle' : ReasoningStyle,
  'response' : string,
  'timestamp' : Timestamp,
  'prompt' : string,
}
export type Mode = { 'Analytics' : null } |
  { 'Text' : null } |
  { 'Image' : null } |
  { 'Music' : null } |
  { 'Video' : null };
export type ReasoningStyle = { 'Creative' : null } |
  { 'Technical' : null } |
  { 'Analytical' : null };
export type Theme = { 'Light' : null } |
  { 'Dark' : null };
export type Timestamp = bigint;
export interface UserSettings {
  'theme' : Theme,
  'defaultMode' : Mode,
  'defaultReasoningStyle' : ReasoningStyle,
}
export interface _SERVICE {
  'clearHistory' : ActorMethod<[], undefined>,
  'deleteHistoryEntry' : ActorMethod<[EntryId], boolean>,
  'getHistory' : ActorMethod<[], Array<HistoryEntry>>,
  'getSettings' : ActorMethod<[], [] | [UserSettings]>,
  'saveHistoryEntry' : ActorMethod<
    [string, Mode, ReasoningStyle, string],
    EntryId
  >,
  'saveSettings' : ActorMethod<[UserSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];