/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface HistoryEntry {
    id: EntryId;
    mode: Mode;
    reasoningStyle: ReasoningStyle;
    response: string;
    timestamp: Timestamp;
    prompt: string;
}
export type EntryId = bigint;
export interface UserSettings {
    theme: Theme;
    defaultMode: Mode;
    defaultReasoningStyle: ReasoningStyle;
}
export enum Mode {
    Analytics = "Analytics",
    Text = "Text",
    Image = "Image",
    Music = "Music",
    Video = "Video"
}
export enum ReasoningStyle {
    Creative = "Creative",
    Technical = "Technical",
    Analytical = "Analytical"
}
export enum Theme {
    Light = "Light",
    Dark = "Dark"
}
export interface backendInterface {
    clearHistory(): Promise<void>;
    deleteHistoryEntry(id: EntryId): Promise<boolean>;
    getHistory(): Promise<Array<HistoryEntry>>;
    getSettings(): Promise<UserSettings | null>;
    saveHistoryEntry(prompt: string, mode: Mode, reasoningStyle: ReasoningStyle, response: string): Promise<EntryId>;
    saveSettings(settings: UserSettings): Promise<void>;
}
import type { EntryId as _EntryId, HistoryEntry as _HistoryEntry, Mode as _Mode, ReasoningStyle as _ReasoningStyle, Theme as _Theme, Timestamp as _Timestamp, UserSettings as _UserSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHistory();
            return result;
        }
    }
    async deleteHistoryEntry(arg0: EntryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHistoryEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHistoryEntry(arg0);
            return result;
        }
    }
    async getHistory(): Promise<Array<HistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<UserSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveHistoryEntry(arg0: string, arg1: Mode, arg2: ReasoningStyle, arg3: string): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHistoryEntry(arg0, to_candid_Mode_n13(this._uploadFile, this._downloadFile, arg1), to_candid_ReasoningStyle_n15(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHistoryEntry(arg0, to_candid_Mode_n13(this._uploadFile, this._downloadFile, arg1), to_candid_ReasoningStyle_n15(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveSettings(arg0: UserSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(to_candid_UserSettings_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(to_candid_UserSettings_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_HistoryEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoryEntry): HistoryEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Mode_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mode): Mode {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ReasoningStyle_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReasoningStyle): ReasoningStyle {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettings_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSettings]): UserSettings | null {
    return value.length === 0 ? null : from_candid_UserSettings_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
    defaultMode: _Mode;
    defaultReasoningStyle: _ReasoningStyle;
}): {
    theme: Theme;
    defaultMode: Mode;
    defaultReasoningStyle: ReasoningStyle;
} {
    return {
        theme: from_candid_Theme_n11(_uploadFile, _downloadFile, value.theme),
        defaultMode: from_candid_Mode_n4(_uploadFile, _downloadFile, value.defaultMode),
        defaultReasoningStyle: from_candid_ReasoningStyle_n6(_uploadFile, _downloadFile, value.defaultReasoningStyle)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    mode: _Mode;
    reasoningStyle: _ReasoningStyle;
    response: string;
    timestamp: _Timestamp;
    prompt: string;
}): {
    id: EntryId;
    mode: Mode;
    reasoningStyle: ReasoningStyle;
    response: string;
    timestamp: Timestamp;
    prompt: string;
} {
    return {
        id: value.id,
        mode: from_candid_Mode_n4(_uploadFile, _downloadFile, value.mode),
        reasoningStyle: from_candid_ReasoningStyle_n6(_uploadFile, _downloadFile, value.reasoningStyle),
        response: value.response,
        timestamp: value.timestamp,
        prompt: value.prompt
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Light: null;
} | {
    Dark: null;
}): Theme {
    return "Light" in value ? Theme.Light : "Dark" in value ? Theme.Dark : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Analytics: null;
} | {
    Text: null;
} | {
    Image: null;
} | {
    Music: null;
} | {
    Video: null;
}): Mode {
    return "Analytics" in value ? Mode.Analytics : "Text" in value ? Mode.Text : "Image" in value ? Mode.Image : "Music" in value ? Mode.Music : "Video" in value ? Mode.Video : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Creative: null;
} | {
    Technical: null;
} | {
    Analytical: null;
}): ReasoningStyle {
    return "Creative" in value ? ReasoningStyle.Creative : "Technical" in value ? ReasoningStyle.Technical : "Analytical" in value ? ReasoningStyle.Analytical : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HistoryEntry>): Array<HistoryEntry> {
    return value.map((x)=>from_candid_HistoryEntry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Mode_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): _Mode {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ReasoningStyle_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReasoningStyle): _ReasoningStyle {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Theme_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserSettings_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserSettings): _UserSettings {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: Theme;
    defaultMode: Mode;
    defaultReasoningStyle: ReasoningStyle;
}): {
    theme: _Theme;
    defaultMode: _Mode;
    defaultReasoningStyle: _ReasoningStyle;
} {
    return {
        theme: to_candid_Theme_n19(_uploadFile, _downloadFile, value.theme),
        defaultMode: to_candid_Mode_n13(_uploadFile, _downloadFile, value.defaultMode),
        defaultReasoningStyle: to_candid_ReasoningStyle_n15(_uploadFile, _downloadFile, value.defaultReasoningStyle)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): {
    Analytics: null;
} | {
    Text: null;
} | {
    Image: null;
} | {
    Music: null;
} | {
    Video: null;
} {
    return value == Mode.Analytics ? {
        Analytics: null
    } : value == Mode.Text ? {
        Text: null
    } : value == Mode.Image ? {
        Image: null
    } : value == Mode.Music ? {
        Music: null
    } : value == Mode.Video ? {
        Video: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReasoningStyle): {
    Creative: null;
} | {
    Technical: null;
} | {
    Analytical: null;
} {
    return value == ReasoningStyle.Creative ? {
        Creative: null
    } : value == ReasoningStyle.Technical ? {
        Technical: null
    } : value == ReasoningStyle.Analytical ? {
        Analytical: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): {
    Light: null;
} | {
    Dark: null;
} {
    return value == Theme.Light ? {
        Light: null
    } : value == Theme.Dark ? {
        Dark: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
